"""Materialize explicit lint source groups; run through Aspect after source changes."""
from __future__ import annotations

import argparse
from collections import defaultdict
import difflib
import json
import os
from pathlib import Path
import subprocess

BEGIN = "# BEGIN generated lint sources"
END = "# END generated lint sources"
EXCLUDED_SUFFIXES = {".gif", ".png", ".jpg", ".ico", ".woff", ".woff2", ".pdf"}
GENERATED_PACKAGES = {
    "modules/picblobs/platforms", "modules/picblobs/toolchains", "modules/picblobs/src/payload",
}


def source_groups(root: Path, paths: list[str]) -> dict[Path, list[str]]:
    groups: dict[Path, list[str]] = defaultdict(list)
    for relative in sorted(set(paths)):
        path = root / relative
        if not path.is_file() or path.is_symlink() or path.suffix in EXCLUDED_SUFFIXES:
            continue
        parent = path.parent
        while parent != root and not (parent / "BUILD.bazel").is_file():
            parent = parent.parent
        build = parent / "BUILD.bazel"
        if build.is_file():
            groups[build].append(path.relative_to(parent).as_posix())
    return dict(groups)


def block(paths: list[str]) -> str:
    # Buildifier compares file stems before extensions (mesh.html before
    # mesh-development.html). Keep materialization stable after formatting.
    paths = sorted(paths, key=lambda path: (str(Path(path).with_suffix("")), Path(path).suffix))
    entries = "\n".join("        " + json.dumps(path) + "," for path in paths)
    return (
        BEGIN + "\nfilegroup(\n"
        '    name = "hovel_lint_sources",\n    srcs = [\n' + entries + "\n    ],\n"
        '    visibility = ["//tools/lint:__pkg__"],\n)\n' + END + "\n"
    )


def replace_block(text: str, replacement: str) -> str:
    if BEGIN in text:
        start = text.index(BEGIN)
        end = text.index(END, start) + len(END)
        return text[:start] + replacement.rstrip() + text[end:]
    return text.rstrip() + "\n\n" + replacement


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(os.environ["BUILD_WORKSPACE_DIRECTORY"])
    paths = subprocess.check_output(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=root
    ).decode().split("\0")
    groups = source_groups(root, [path for path in paths if path])
    outputs = {}
    for path, files in groups.items():
        text = path.read_text()
        if path.parent.relative_to(root).as_posix() in GENERATED_PACKAGES:
            # These generators already expose the package's declared quality
            # sources. Do not append to another generator's output contract.
            outputs[path] = text.split(BEGIN, 1)[0].rstrip() + "\n"
        else:
            outputs[path] = replace_block(text, block(files))
    for workspace in (root, root / "core"):
        labels = []
        for build in sorted(groups):
            if workspace == root and build.is_relative_to(root / "core"):
                continue
            if not build.is_relative_to(workspace):
                continue
            package = build.parent.relative_to(workspace).as_posix()
            target_name = "quality_sources" if package in GENERATED_PACKAGES else "hovel_lint_sources"
            labels.append("//" + ("" if package == "." else package) + ":" + target_name)
        target = workspace / "tools/lint/sources.bzl"
        outputs[target] = '"""Generated by aspect hovel-format; do not edit."""\n\nLINT_SOURCE_GROUPS = [\n' + "".join("    " + json.dumps(label) + ",\n" for label in labels) + "]\n"
    changed = [path for path, text in outputs.items() if not path.exists() or path.read_text() != text]
    if args.check:
        for path in changed:
            print("stale lint source declaration:", path.relative_to(root))
            existing = path.read_text() if path.exists() else ""
            print("".join(list(difflib.unified_diff(existing.splitlines(True), outputs[path].splitlines(True)))[:35]))
        return int(bool(changed))
    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(outputs[path])
    print(f"Updated {len(changed)} lint source declarations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
