# Generated by tools/generate.py from tools/registry.py — DO NOT EDIT.
"""Repository definitions for picblobs external toolchains."""

load(":arm_none_eabi.bzl", "arm_none_eabi_repo")
load(":bootlin.bzl", "bootlin_toolchain_repo")
load(":qemu.bzl", "qemu_arm_repo", "qemu_user_static_repo")

_ARM_NONE_EABI_TOOLCHAIN = struct(
    extra_cflags = ["-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=soft"],
    sha256 = "95c011cee430e64dd6087c75c800f04b9c49832cc1000127a92a97f9c8d83af4",
    strip_prefix = "arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi",
    url = "https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz",
)

_MBED_ARM_NONE_EABI_TOOLCHAIN = struct(
    extra_cflags = ["-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=soft"],
    sha256 = "bcd840f839d5bf49279638e9f67890b2ef3a7c9c7a9b25271e83ec4ff41d177a",
    strip_prefix = "gcc-arm-none-eabi-9-2019-q4-major",
    url = "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2",
)

_BOOTLIN_TOOLCHAINS = [
    struct(
        name = "x86_64",
        arch = "x86-64",
        extra_cflags = ["-march=x86-64"],
        libc = "glibc",
        sha256 = "932823ca9a3e067e7e2a29810a666d20c9cc5bb550de947f6879e38ace1aa955",
        triple = "x86_64-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "i686",
        arch = "x86-i686",
        extra_cflags = ["-march=i686"],
        libc = "glibc",
        sha256 = "023e4f03cd212b5545c4c184238693b61b40fa36d257b84546100a92ea2c1d8b",
        triple = "i686-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "aarch64",
        arch = "aarch64",
        extra_cflags = [],
        libc = "glibc",
        sha256 = "b0fad860eb94b503a56d66ca8b9ba06d2d4826943e37ebd1d7217423f6ea5bb2",
        triple = "aarch64-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "armv5",
        arch = "armv5-eabi",
        extra_cflags = ["-march=armv5te"],
        libc = "glibc",
        sha256 = "13f2bea0b06fe560fe60d199cd9d3fb1f20e2335bcc79b90c5130c3916a3ed92",
        triple = "arm-buildroot-linux-gnueabi",
        version = "2024.05-1",
    ),
    struct(
        name = "armv7",
        arch = "armv7-eabihf",
        extra_cflags = ["-march=armv7-a", "-mthumb"],
        libc = "glibc",
        sha256 = "608263bc9dc3eadf0962ddb1165f1c2291001190f9927dee47d464e26374462c",
        triple = "arm-buildroot-linux-gnueabihf",
        version = "2024.05-1",
    ),
    struct(
        name = "mipsel32",
        arch = "mips32el",
        extra_cflags = ["-mips32", "-EL"],
        libc = "glibc",
        sha256 = "d0139b6ade7f3b72a5f9c33814696af817661e826c9c501f6cefcab4ac684c8f",
        triple = "mipsel-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "s390x",
        arch = "s390x-z13",
        extra_cflags = ["-march=z13"],
        libc = "glibc",
        sha256 = "b37ed02693a370f28434c34655c64bcb96dc0d428a92ddbc99feb5608bcf64a1",
        triple = "s390x-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "mipsbe32",
        arch = "mips32",
        extra_cflags = ["-mips32", "-EB"],
        libc = "glibc",
        sha256 = "677402719c545e49eb71c3d27a5f495af38f60463b40ed705e24e43a9834c137",
        triple = "mips-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "sparcv8",
        arch = "sparcv8",
        extra_cflags = ["-mcpu=v8"],
        libc = "uclibc",
        sha256 = "8ec2c84b84a13b854a13802537f0b04848056ebc65f6212202f6d8c8a78d4bc3",
        triple = "sparc-buildroot-linux-uclibc",
        version = "2024.05-1",
    ),
    struct(
        name = "powerpc",
        arch = "powerpc-e300c3",
        extra_cflags = ["-mcpu=e300c3"],
        libc = "glibc",
        sha256 = "6c975a7293fde77a52f348124049645ee2ceee19e75ab6e0b2364043090a2dff",
        triple = "powerpc-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "ppc64le",
        arch = "powerpc64le-power8",
        extra_cflags = ["-mcpu=power8"],
        libc = "glibc",
        sha256 = "8133b74614f880eb8b76730efee77b8fd281c982bfa2791b72c5f836a529530d",
        triple = "powerpc64le-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
    struct(
        name = "riscv64",
        arch = "riscv64-lp64d",
        extra_cflags = [],
        libc = "glibc",
        sha256 = "78e16f3def8b2ff3da09c16155f993ac7e4dc1791d0904ada03fcb2e04910aab",
        triple = "riscv64-buildroot-linux-gnu",
        version = "2024.05-1",
    ),
]

def _picblobs_toolchains_impl(_module_ctx):
    arm_none_eabi_repo(
        name = "arm_none_eabi",
        extra_cflags = _ARM_NONE_EABI_TOOLCHAIN.extra_cflags,
        sha256 = _ARM_NONE_EABI_TOOLCHAIN.sha256,
        strip_prefix = _ARM_NONE_EABI_TOOLCHAIN.strip_prefix,
        url = _ARM_NONE_EABI_TOOLCHAIN.url,
    )
    arm_none_eabi_repo(
        name = "mbed_arm_none_eabi",
        extra_cflags = _MBED_ARM_NONE_EABI_TOOLCHAIN.extra_cflags,
        sha256 = _MBED_ARM_NONE_EABI_TOOLCHAIN.sha256,
        strip_prefix = _MBED_ARM_NONE_EABI_TOOLCHAIN.strip_prefix,
        url = _MBED_ARM_NONE_EABI_TOOLCHAIN.url,
    )
    for toolchain in _BOOTLIN_TOOLCHAINS:
        repo_name = "bootlin_{}".format(toolchain.name)
        bootlin_toolchain_repo(
            name = repo_name,
            arch = toolchain.arch,
            extra_cflags = toolchain.extra_cflags,
            libc = toolchain.libc,
            sha256 = toolchain.sha256,
            target_cpu = toolchain.name,
            toolchain_id = repo_name,
            triple = toolchain.triple,
            version = toolchain.version,
        )
    qemu_user_static_repo(name = "qemu_user_static")
    qemu_arm_repo(name = "qemu_arm_static")

picblobs_toolchains = module_extension(
    implementation = _picblobs_toolchains_impl,
)
