# Generated by tools/generate.py from tools/registry.py — DO NOT EDIT.
"""Repository definitions for picblobs external toolchains."""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load(":arm_none_eabi.bzl", "arm_none_eabi_repo")
load(":bootlin.bzl", "bootlin_toolchain_repo")
load(":qemu.bzl", "qemu_arm_repo", "qemu_user_static_repo")

_ARM_NONE_EABI_TOOLCHAIN = struct(
    extra_cflags = ["-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=soft"],
    sha256 = "597893282ac8c6ab1a4073977f2362990184599643b4c5ee34870a8215783a16",
    strip_prefix = "arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi",
    url = "https://developer.arm.com/-/media/Files/downloads/gnu/15.2.rel1/binrel/arm-gnu-toolchain-15.2.rel1-x86_64-arm-none-eabi.tar.xz",
)

_MBED_ARM_NONE_EABI_TOOLCHAIN = struct(
    extra_cflags = ["-mcpu=cortex-m4", "-mthumb", "-mfloat-abi=soft"],
    sha256 = "bcd840f839d5bf49279638e9f67890b2ef3a7c9c7a9b25271e83ec4ff41d177a",
    strip_prefix = "gcc-arm-none-eabi-9-2019-q4-major",
    url = "https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2",
)

_MBED_OS_SOURCE = struct(
    commit = "dfcb61e052d1192d99a07dca6fb4970281afc8e4",
    sha256 = "9bdcfd5f65542988461c6c33a1ae376e6fd1cb4c1f2786a4f6cd63522b843c14",
    url = "https://github.com/ARMmbed/mbed-os/archive/dfcb61e052d1192d99a07dca6fb4970281afc8e4.tar.gz",
)

_BOOTLIN_TOOLCHAINS = [
    struct(
        name = "x86_64",
        arch = "x86-64",
        extra_cflags = ["-march=x86-64"],
        libc = "glibc",
        sha256 = "760acd5c3159448b618e237b61935335baada74fe0cdc0d7611826cb49b41c8c",
        triple = "x86_64-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "i686",
        arch = "x86-i686",
        extra_cflags = ["-march=i686"],
        libc = "glibc",
        sha256 = "f9b365d7fd8f8860dfb1845ff731013550f071ca4a8de0e5074abc995296b26c",
        triple = "i686-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "aarch64",
        arch = "aarch64",
        extra_cflags = [],
        libc = "glibc",
        sha256 = "dfb47eee874eef9e8a7fc042eee4e0a183f444b6bcde6a82fef8f009918389c9",
        triple = "aarch64-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "armv5",
        arch = "armv5-eabi",
        extra_cflags = ["-march=armv5te"],
        libc = "glibc",
        sha256 = "53f3d7c2b0ce32f120043bf4b338b3ea3f3375015ed63f5b382a5f62894baeec",
        triple = "arm-buildroot-linux-gnueabi",
        version = "2025.08-1",
    ),
    struct(
        name = "armv7",
        arch = "armv7-eabihf",
        extra_cflags = ["-march=armv7-a", "-mthumb"],
        libc = "glibc",
        sha256 = "97d6fbaf19832002f3d6aa8fd31b2d29c1dc7b0752f4ae8ed35860fd33c1f9b4",
        triple = "arm-buildroot-linux-gnueabihf",
        version = "2025.08-1",
    ),
    struct(
        name = "mipsel32",
        arch = "mips32el",
        extra_cflags = ["-mips32", "-EL"],
        libc = "glibc",
        sha256 = "1085fe6b13d74205ef6e92d1d40fb3960bf6e4bad50555c723fa07416cb53c1c",
        triple = "mipsel-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "s390x",
        arch = "s390x-z13",
        extra_cflags = ["-march=z13"],
        libc = "glibc",
        sha256 = "4e67f2751487493c2d68aab643de22a6e8cf81e6d918125b96b50eb5e02a85d5",
        triple = "s390x-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "mipsbe32",
        arch = "mips32",
        extra_cflags = ["-mips32", "-EB"],
        libc = "glibc",
        sha256 = "23d0f36aa7962230ef43338ba14ac2a7fa6eb68e15ef39cb9114ac711b907f70",
        triple = "mips-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "sparcv8",
        arch = "sparcv8",
        extra_cflags = ["-mcpu=v8"],
        libc = "uclibc",
        sha256 = "5d099c4ecdac8e030e04e5b5139e635a9a1faa64bb77f452b33ef469f93b6e46",
        triple = "sparc-buildroot-linux-uclibc",
        version = "2025.08-1",
    ),
    struct(
        name = "powerpc",
        arch = "powerpc-e300c3",
        extra_cflags = ["-mcpu=e300c3"],
        libc = "glibc",
        sha256 = "581d0441a31bff4f3a0996b824afb3fe35c6c32f543765b28a6b63a5684fc116",
        triple = "powerpc-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "ppc64le",
        arch = "powerpc64le-power8",
        extra_cflags = ["-mcpu=power8"],
        libc = "glibc",
        sha256 = "819c8dee94b1baff33943f3b01d669ea794a825e7b4cbead340ad5de8cff6baa",
        triple = "powerpc64le-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
    struct(
        name = "riscv64",
        arch = "riscv64-lp64d",
        extra_cflags = [],
        libc = "glibc",
        sha256 = "45209041e9ba5054aa9787c40bce0ac1e48b78528b6635b79dfb4253e1491ff0",
        triple = "riscv64-buildroot-linux-gnu",
        version = "2025.08-1",
    ),
]

def _picblobs_toolchains_impl(_module_ctx):
    arm_none_eabi_repo(
        name = "arm_none_eabi",
        extra_cflags = _ARM_NONE_EABI_TOOLCHAIN.extra_cflags,
        sha256 = _ARM_NONE_EABI_TOOLCHAIN.sha256,
        strip_prefix = _ARM_NONE_EABI_TOOLCHAIN.strip_prefix,
        url = _ARM_NONE_EABI_TOOLCHAIN.url,
    )
    arm_none_eabi_repo(
        name = "mbed_arm_none_eabi",
        extra_cflags = _MBED_ARM_NONE_EABI_TOOLCHAIN.extra_cflags,
        sha256 = _MBED_ARM_NONE_EABI_TOOLCHAIN.sha256,
        strip_prefix = _MBED_ARM_NONE_EABI_TOOLCHAIN.strip_prefix,
        url = _MBED_ARM_NONE_EABI_TOOLCHAIN.url,
    )
    http_archive(
        name = "mbed_os_5_15_9",
        build_file_content = "\n".join([
            "package(default_visibility = [\"//visibility:public\"])",
            "",
            "filegroup(",
            "    name = \"all_files\",",
            "    srcs = glob([\"**\"]),",
            ")",
            "",
            "filegroup(",
            "    name = \"version_header\",",
            "    srcs = [\"platform/mbed_version.h\"],",
            ")",
            "",
        ]),
        sha256 = _MBED_OS_SOURCE.sha256,
        strip_prefix = "mbed-os-{}".format(_MBED_OS_SOURCE.commit),
        urls = [_MBED_OS_SOURCE.url],
    )
    for toolchain in _BOOTLIN_TOOLCHAINS:
        repo_name = "bootlin_{}".format(toolchain.name)
        bootlin_toolchain_repo(
            name = repo_name,
            arch = toolchain.arch,
            extra_cflags = toolchain.extra_cflags,
            libc = toolchain.libc,
            sha256 = toolchain.sha256,
            target_cpu = toolchain.name,
            toolchain_id = repo_name,
            triple = toolchain.triple,
            version = toolchain.version,
        )
    qemu_user_static_repo(name = "qemu_user_static")
    qemu_arm_repo(name = "qemu_arm_static")

picblobs_toolchains = module_extension(
    implementation = _picblobs_toolchains_impl,
)
