"""Canonical NaCl blob wire/config contract and C-header generator."""

from __future__ import annotations

import ipaddress
import struct

AUTH_KEY_SIZE = 32
PORT_SIZE = 2
IPV4_SIZE = 4
MIN_PORT = 1
MAX_PORT = (1 << (PORT_SIZE * 8)) - 1

SERVER_PORT_OFFSET = 0
SERVER_AUTH_KEY_OFFSET = SERVER_PORT_OFFSET + PORT_SIZE
SERVER_CONFIG_SIZE = SERVER_AUTH_KEY_OFFSET + AUTH_KEY_SIZE

CLIENT_PORT_OFFSET = 0
CLIENT_IPV4_OFFSET = CLIENT_PORT_OFFSET + PORT_SIZE
CLIENT_AUTH_KEY_OFFSET = CLIENT_IPV4_OFFSET + IPV4_SIZE
CLIENT_CONFIG_SIZE = CLIENT_AUTH_KEY_OFFSET + AUTH_KEY_SIZE

NONCE_SIZE = 24
FRAME_LENGTH_SIZE = 4
FRAME_HEADER_SIZE = NONCE_SIZE + FRAME_LENGTH_SIZE
SECRETBOX_OVERHEAD = 16
HANDSHAKE_PUBLIC_KEY_SIZE = 32
MAX_PLAINTEXT_SIZE = 4096
PORT_FORMAT = "<H"
FRAME_LENGTH_FORMAT = "<I"

DEFAULT_PORT = 9999
DEFAULT_SERVER_IPV4 = "127.0.0.1"
CLIENT_MESSAGE = "Hello from NaCl PIC blob!"
SERVER_ACK = "hovel-nacl-server-ack-v1"

DEFAULT_PORT_BYTES = struct.pack(PORT_FORMAT, DEFAULT_PORT)
DEFAULT_SERVER_IPV4_BYTES = ipaddress.IPv4Address(DEFAULT_SERVER_IPV4).packed
SERVER_CONFIG_TEMPLATE = DEFAULT_PORT_BYTES + bytes(AUTH_KEY_SIZE)
CLIENT_CONFIG_TEMPLATE = (
    DEFAULT_PORT_BYTES + DEFAULT_SERVER_IPV4_BYTES + bytes(AUTH_KEY_SIZE)
)


def render_c_header() -> str:
    """Render the checked-in C contract consumed by both payload roles."""

    port_bytes = ", ".join(f"0x{value:02x}" for value in DEFAULT_PORT_BYTES)
    ipv4_bytes = ", ".join(str(value) for value in DEFAULT_SERVER_IPV4_BYTES)
    return f"""/* Generated by modules/picblobs/nacl_protocol.py; do not edit. */
#ifndef PICBLOBS_NACL_PROTOCOL_H
#define PICBLOBS_NACL_PROTOCOL_H

#define NACL_AUTH_KEY_SIZE {AUTH_KEY_SIZE}U
#define NACL_PORT_SIZE {PORT_SIZE}U
#define NACL_IPV4_SIZE {IPV4_SIZE}U

#define NACL_SERVER_PORT_OFFSET {SERVER_PORT_OFFSET}U
#define NACL_SERVER_AUTH_KEY_OFFSET {SERVER_AUTH_KEY_OFFSET}U
#define NACL_SERVER_CONFIG_SIZE {SERVER_CONFIG_SIZE}U

#define NACL_CLIENT_PORT_OFFSET {CLIENT_PORT_OFFSET}U
#define NACL_CLIENT_IPV4_OFFSET {CLIENT_IPV4_OFFSET}U
#define NACL_CLIENT_AUTH_KEY_OFFSET {CLIENT_AUTH_KEY_OFFSET}U
#define NACL_CLIENT_CONFIG_SIZE {CLIENT_CONFIG_SIZE}U

#define NACL_NONCE_SIZE {NONCE_SIZE}U
#define NACL_FRAME_LENGTH_SIZE {FRAME_LENGTH_SIZE}U
#define NACL_FRAME_HEADER_SIZE {FRAME_HEADER_SIZE}U
#define NACL_SECRETBOX_OVERHEAD {SECRETBOX_OVERHEAD}U
#define NACL_HANDSHAKE_PUBLIC_KEY_SIZE {HANDSHAKE_PUBLIC_KEY_SIZE}U
#define NACL_MAX_PLAINTEXT_SIZE {MAX_PLAINTEXT_SIZE}U

#define NACL_CLIENT_MESSAGE \"{CLIENT_MESSAGE}\"
#define NACL_SERVER_ACK \"{SERVER_ACK}\"

#define NACL_DEFAULT_PORT_ASM \".byte {port_bytes}\\n\"
#define NACL_DEFAULT_SERVER_IPV4_ASM \".byte {ipv4_bytes}\\n\"
#define NACL_AUTH_KEY_RESERVATION_ASM \".skip {AUTH_KEY_SIZE}, 0\\n\"

#define NACL_ASSERT(name, expr) typedef char name##_assertion[((expr) ? 1 : -1)]

struct nacl_server_config_layout {{
\tunsigned char port[NACL_PORT_SIZE];
\tunsigned char auth_key[NACL_AUTH_KEY_SIZE];
}};

struct nacl_client_config_layout {{
\tunsigned char port[NACL_PORT_SIZE];
\tunsigned char server_ipv4[NACL_IPV4_SIZE];
\tunsigned char auth_key[NACL_AUTH_KEY_SIZE];
}};

NACL_ASSERT(nacl_server_config_size_matches,
\tsizeof(struct nacl_server_config_layout) == NACL_SERVER_CONFIG_SIZE);
NACL_ASSERT(nacl_server_auth_key_offset_matches,
\t__builtin_offsetof(struct nacl_server_config_layout, auth_key) ==
\t\tNACL_SERVER_AUTH_KEY_OFFSET);
NACL_ASSERT(nacl_client_config_size_matches,
\tsizeof(struct nacl_client_config_layout) == NACL_CLIENT_CONFIG_SIZE);
NACL_ASSERT(nacl_client_ipv4_offset_matches,
\t__builtin_offsetof(struct nacl_client_config_layout, server_ipv4) ==
\t\tNACL_CLIENT_IPV4_OFFSET);
NACL_ASSERT(nacl_client_auth_key_offset_matches,
\t__builtin_offsetof(struct nacl_client_config_layout, auth_key) ==
\t\tNACL_CLIENT_AUTH_KEY_OFFSET);

#endif /* PICBLOBS_NACL_PROTOCOL_H */
"""
