load("@picblobs_pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "release_lib",
    srcs = ["release_tool.py"],
    imports = ["."],
    deps = [requirement("click")],
)

py_binary(
    name = "release_tool",
    srcs = ["release_main.py"],
    main = "release_main.py",
    python_version = "PY3",
    deps = [":release_lib"],
)

py_test(
    name = "release_tool_test",
    size = "small",
    srcs = ["release_tool_test.py"],
    main = "release_tool_test.py",
    python_version = "PY3",
    deps = [":release_lib"],
)

# BEGIN generated lint sources
filegroup(
    name = "hovel_lint_sources",
    srcs = [
        "BUILD.bazel",
        "release_main.py",
        "release_tool.py",
        "release_tool_test.py",
    ],
    visibility = ["//tools/lint:__pkg__"],
)
# END generated lint sources
