/* Generated by modules/picblobs/nacl_protocol.py; do not edit. */
#ifndef PICBLOBS_NACL_PROTOCOL_H
#define PICBLOBS_NACL_PROTOCOL_H

#define NACL_AUTH_KEY_SIZE 32U
#define NACL_PORT_SIZE 2U
#define NACL_IPV4_SIZE 4U

#define NACL_SERVER_PORT_OFFSET 0U
#define NACL_SERVER_AUTH_KEY_OFFSET 2U
#define NACL_SERVER_CONFIG_SIZE 34U

#define NACL_CLIENT_PORT_OFFSET 0U
#define NACL_CLIENT_IPV4_OFFSET 2U
#define NACL_CLIENT_AUTH_KEY_OFFSET 6U
#define NACL_CLIENT_CONFIG_SIZE 38U

#define NACL_NONCE_SIZE 24U
#define NACL_FRAME_LENGTH_SIZE 4U
#define NACL_FRAME_HEADER_SIZE 28U
#define NACL_SECRETBOX_OVERHEAD 16U
#define NACL_HANDSHAKE_PUBLIC_KEY_SIZE 32U
#define NACL_MAX_PLAINTEXT_SIZE 4096U

#define NACL_CLIENT_MESSAGE "Hello from NaCl PIC blob!"
#define NACL_SERVER_ACK "hovel-nacl-server-ack-v1"

#define NACL_DEFAULT_PORT_ASM ".byte 0x0f, 0x27\n"
#define NACL_DEFAULT_SERVER_IPV4_ASM ".byte 127, 0, 0, 1\n"
#define NACL_AUTH_KEY_RESERVATION_ASM ".skip 32, 0\n"

#define NACL_ASSERT(name, expr) typedef char name##_assertion[((expr) ? 1 : -1)]

struct nacl_server_config_layout {
	unsigned char port[NACL_PORT_SIZE];
	unsigned char auth_key[NACL_AUTH_KEY_SIZE];
};

struct nacl_client_config_layout {
	unsigned char port[NACL_PORT_SIZE];
	unsigned char server_ipv4[NACL_IPV4_SIZE];
	unsigned char auth_key[NACL_AUTH_KEY_SIZE];
};

NACL_ASSERT(nacl_server_config_size_matches,
	sizeof(struct nacl_server_config_layout) == NACL_SERVER_CONFIG_SIZE);
NACL_ASSERT(nacl_server_auth_key_offset_matches,
	__builtin_offsetof(struct nacl_server_config_layout, auth_key) ==
		NACL_SERVER_AUTH_KEY_OFFSET);
NACL_ASSERT(nacl_client_config_size_matches,
	sizeof(struct nacl_client_config_layout) == NACL_CLIENT_CONFIG_SIZE);
NACL_ASSERT(nacl_client_ipv4_offset_matches,
	__builtin_offsetof(struct nacl_client_config_layout, server_ipv4) ==
		NACL_CLIENT_IPV4_OFFSET);
NACL_ASSERT(nacl_client_auth_key_offset_matches,
	__builtin_offsetof(struct nacl_client_config_layout, auth_key) ==
		NACL_CLIENT_AUTH_KEY_OFFSET);

#endif /* PICBLOBS_NACL_PROTOCOL_H */
