"""Repository rule that turns a published MinGW-w64 toolchain tarball into a
Bazel `cc_toolchain`.

Why a custom rule instead of a plain `http_archive` + `build_file_content`?
Bazel's strict-header machinery rejects any `#include` that resolves outside a
*declared* builtin include directory ("undeclared inclusion(s)"). The set of
those directories is a property of the compiler (it moves with the GCC version,
the multilib layout, and `include-fixed`). Hardcoding
`lib/gcc/<target>/15.2.0/include` would silently rot on the next toolchain bump.

So at repository-fetch time we *ask the compiler* where it looks:

    <target>-gcc -E -x c -v - < /dev/null

and parse the `#include <...> search starts here:` block out of stderr. Those
absolute paths are handed to the upstream `mingw_cc_toolchain` helper
(`@windows_toolchains//bazel:consume.bzl`) as `builtin_include_dirs`. The result
is a toolchain definition that re-derives itself from whatever tarball it is
pointed at -- no per-version edits.
"""

def _probe_builtin_include_dirs(rctx, gcc_path):
    """Return the compiler's system include search list, normalized + absolute.

    Runs the preprocessor over an empty file with `-v` and scrapes the
    canonical search-list block. Fails loudly if the block is absent or empty:
    a silent empty list would resurface later as a flood of undeclared-inclusion
    errors far from the cause.
    """
    probe_src = rctx.path("_probe.c")
    rctx.file(probe_src, "", executable = False)
    result = rctx.execute(
        [gcc_path, "-E", "-x", "c", "-v", str(probe_src)],
        quiet = True,
    )
    if result.return_code != 0:
        fail("probing builtin include dirs failed (exit %d):\n%s" % (
            result.return_code,
            result.stderr,
        ))

    dirs = []
    capturing = False
    for raw in result.stderr.splitlines():
        line = raw.strip()
        if line.startswith("#include <...> search starts here:"):
            capturing = True
            continue
        if line.startswith("End of search list."):
            break
        if capturing and line:
            # rctx.path() realpaths the entry, collapsing the `bin/../lib/...`
            # segments GCC prints so the strings match what the sandbox sees.
            dirs.append(str(rctx.path(line)))

    if not dirs:
        fail("no builtin include dirs parsed from gcc -v output:\n%s" % result.stderr)
    return dirs

def _mingw_toolchain_repo_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        stripPrefix = rctx.attr.strip_prefix,
    )

    gcc = rctx.path("bin/{}-gcc".format(rctx.attr.target))
    if not gcc.exists:
        fail("expected cross gcc not found in tarball: {}".format(gcc))

    include_dirs = _probe_builtin_include_dirs(rctx, gcc)

    rctx.file(
        "BUILD.bazel",
        """# Generated by //payloads/squatter/bazel:mingw.bzl -- do not edit by hand.
load("@hovel//payloads/squatter/bazel:mingw_toolchain.bzl", "mingw_cc_toolchain")

package(default_visibility = ["//visibility:public"])

mingw_cc_toolchain(
    name = "toolchain",
    target = {target},
    cpu = {cpu},
    static_runtime = {static_runtime},
    builtin_include_dirs = {include_dirs},
)
""".format(
            target = repr(rctx.attr.target),
            cpu = repr(rctx.attr.cpu),
            static_runtime = repr(rctx.attr.static_runtime),
            include_dirs = repr(include_dirs),
        ),
    )

mingw_toolchain_repo = repository_rule(
    implementation = _mingw_toolchain_repo_impl,
    doc = "Fetch a windows-toolchains release tarball and expose //:toolchain.",
    attrs = {
        "urls": attr.string_list(
            mandatory = True,
            doc = "Mirror list for the release .tar.xz asset.",
        ),
        "sha256": attr.string(
            mandatory = True,
            doc = "Pinned SHA256 of the tarball (from the published .sha256 asset).",
        ),
        "strip_prefix": attr.string(
            mandatory = True,
            doc = "Top-level directory inside the tarball.",
        ),
        "target": attr.string(
            mandatory = True,
            doc = "GNU triple, e.g. x86_64-w64-mingw32 or i686-w64-mingw32.",
        ),
        "cpu": attr.string(
            mandatory = True,
            doc = "Bazel target_cpu: x86_64 or x86_32.",
        ),
        "static_runtime": attr.bool(
            default = True,
            doc = "Statically link libgcc/libstdc++/winpthreads into the .exe.",
        ),
    },
)
